# Generated by Django 5.1.3 on 2024-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=50)),
                ('requisition_day', models.IntegerField()),
                ('data_criation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('price_product', models.FloatField(max_length=200)),
                ('data_criation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supliers',
            fields=[
                ('id_suplier', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_enterprise', models.CharField(max_length=50)),
                ('data_criation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
