# Generated by Django 4.2.17 on 2025-02-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supliers',
            new_name='Enterprise',
        ),
    ]
