# Generated by Django 4.2.17 on 2025-02-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_rename_supliers_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id_suplier', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_enterprise', models.CharField(max_length=50)),
                ('data_criation', models.DateTimeField(auto_now_add=True)),
                ('refer_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parceiros.products')),
            ],
        ),
        migrations.RenameModel(
            old_name='clientes',
            new_name='clients',
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
